"use strict";

module.exports = {
    rules: {
        // ESLint
        "default-case-last": "off",
        "default-param-last": "off",
        eqeqeq: "off",
        "for-direction": "off",
        "no-async-promise-executor": "off",
        "no-case-declarations": "off",
        "no-compare-neg-zero": "off",
        "no-const-assign": "off",
        "no-constructor-return": "off",
        "no-debugger": "off",
        "no-delete-var": "off",
        "no-dupe-keys": "off",
        "no-ex-assign": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-label-var": "off",
        "no-loss-of-precision": "off",
        "no-negated-condition": "off",
        "no-new-symbol": "off",
        "no-regex-spaces": "off",
        "no-setter-return": "off",
        "no-shadow-restricted-names": "off",
        "no-sparse-arrays": "off",
        "no-undef": "off",
        "no-unreachable": "off",
        "no-unsafe-finally": "off",
        "no-unsafe-negation": "off",
        "no-unused-vars": "off",
        "no-var": "off",
        "one-var": "off",
        "prefer-const": "off",
        "prefer-exponentiation-operator": "off",
        "prefer-numeric-literals": "off",
        "prefer-rest-params": "off",
        "prefer-template": "off",
        "sort-imports": "off",
        "valid-typeof": "off",

        // Typescript
        "@typescript-eslint/array-type": "off",
        "@typescript-eslint/default-param-last": "off",
        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/no-empty-interface": "off",
        "@typescript-eslint/no-extra-non-null-assertion": "off",
        "@typescript-eslint/no-loss-of-precision": "off",
        "@typescript-eslint/no-non-null-assertion": "off",
        "@typescript-eslint/no-unused-vars": "off",
        "@typescript-eslint/prefer-enum-initializers": "off",

        // Unicorn
        "unicorn/no-extra-boolean-cast": "off",
        "unicorn/no-negated-condition": "off",
        "unicorn/prefer-array-flat-map": "off",

        // React
        "react/button-has-type": "off",
        "react/no-array-index-key": "off",
        "react/no-children-prop": "off",
        "react/no-danger-with-children": "off",
        "react/no-render-return-value": "off",
        "react/self-closing-comp": "off",
        "react/void-dom-elements-no-children": "off",
        "react/jsx-boolean-value": "off",
        "react/jsx-fragments": "off",
        "react/jsx-no-blank-target": "off",
        "react/jsx-no-comment-textnodes": "off",
        "react/jsx-no-useless-fragment": "off",
    },
};