import reactX from "@eslint-react/eslint-plugin";
import stylistic from "@stylistic/eslint-plugin";
import typescriptEslint from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import importPlugin from "eslint-plugin-import-x";
import jest from "eslint-plugin-jest";
import testingLibrary from "eslint-plugin-testing-library";
import unicorn from "eslint-plugin-unicorn";
import globals from "globals";

// biome-ignore lint/style/noDefaultExport: Required for ESLint configuration
export default [
	{
		plugins: {
			react: reactX,
			"@stylistic": stylistic,
			unicorn,
			importPlugin,
		},
		linterOptions: {
			reportUnusedDisableDirectives: true,
		},
		languageOptions: {
			globals: {
				...globals.node,
			},
			ecmaVersion: "latest",
			sourceType: "commonjs",
			parserOptions: {
				ecmaFeatures: {
					globalReturn: false,
					impliedStrict: false,
					jsx: true,
				},
			},
		},
		settings: {
			"react-x": {
				version: "detect",
				importSource: "react",
				polymorphicPropName: "as",
			},
		},
		rules: {
			// Possible problems
			"array-callback-return": [
				"error",
				{
					allowImplicit: true,
					checkForEach: false,
				},
			],
			"constructor-super": "off",
			"for-direction": "off",
			"getter-return": "off",
			"no-async-promise-executor": "off",
			"no-await-in-loop": "off",
			"no-class-assign": "off",
			"no-compare-neg-zero": "off",
			"no-cond-assign": "off",
			"no-const-assign": "off",
			"no-constant-binary-expression": "off",
			"no-constant-condition": "off",
			"no-constructor-return": "off",
			"no-control-regex": "off",
			"no-debugger": "off",
			"no-dupe-args": "off",
			"no-dupe-class-members": "off",
			"no-dupe-else-if": "off",
			"no-dupe-keys": "off",
			"no-duplicate-case": "off",
			"no-duplicate-imports": "off",
			"no-empty-character-class": "off",
			"no-empty-pattern": "off",
			"no-ex-assign": "off",
			"no-fallthrough": "off",
			"no-func-assign": "off",
			"no-import-assign": "off",
			"no-inner-declarations": "off",
			"no-invalid-regexp": "error",
			"no-irregular-whitespace": "off",
			"no-loss-of-precision": "off",
			"no-misleading-character-class": "off",
			"no-new-native-nonconstructor": "off",
			"no-new-symbol": "off",
			"no-obj-calls": "off",
			"no-promise-executor-return": "error",
			"no-prototype-builtins": "off",
			"no-self-assign": "off",
			"no-self-compare": "off",
			"no-setter-return": "off",
			"no-sparse-arrays": "off",
			"no-template-curly-in-string": "off",
			"no-this-before-super": "off",
			"no-undef": "off",
			"no-unexpected-multiline": "error",
			"no-unmodified-loop-condition": "error",
			"no-unreachable": "off",
			"no-unreachable-loop": "error",
			"no-unsafe-finally": "off",
			"no-unsafe-negation": "off",
			"no-unsafe-optional-chaining": "off",
			"no-unused-private-class-members": "off",
			"no-unused-vars": "off",
			"no-use-before-define": "off",
			"no-useless-assignment": "error",
			"no-useless-backreference": "off",
			"require-atomic-updates": "error",
			"use-isnan": "off",
			"valid-typeof": "off",

			// Suggestions
			"accessor-pairs": [
				"error",
				{
					getWithoutSet: false,
					setWithoutGet: true,
					enforceForClassMembers: true,
				},
			],
			"arrow-body-style": "off",
			"block-scoped-var": "error",
			camelcase: "off",
			"capitalized-comments": "off",
			"class-methods-use-this": "off",
			complexity: "off",
			"consistent-return": "error",
			"consistent-this": ["error", "that"],
			curly: "off",
			"default-case": "off",
			"default-case-last": "off",
			"default-param-last": "off",
			"dot-notation": "off",
			eqeqeq: "off",
			"func-name-matching": "off",
			"func-names": "off",
			"func-style": [
				"error",
				"declaration",
				{
					allowArrowFunctions: true,
				},
			],
			"grouped-accessor-pairs": "off",
			"guard-for-in": "off",
			"id-denylist": "off",
			"id-length": [
				"error",
				{
					exceptions: ["_", "i", "j", "x", "y", "z"],
				},
			],
			"id-match": "off",
			"init-declarations": "off",
			"logical-assignment-operators": "error",
			"max-classes-per-file": "off",
			"max-depth": "off",
			"max-lines": "off",
			"max-lines-per-function": "off",
			"max-nested-callbacks": "off",
			"max-params": "off",
			"max-statements": "off",
			"multiline-comment-style": "off",
			"new-cap": "error",
			"no-alert": "off",
			"no-array-constructor": "off",
			"no-bitwise": "off",
			"no-caller": "error",
			"no-case-declarations": "off",
			"no-console": "off",
			"no-continue": "off",
			"no-delete-var": "off",
			"no-div-regex": "off",
			"no-else-return": "off",
			"no-empty": "off",
			"no-empty-function": "off",
			"no-empty-static-block": "off",
			"no-eq-null": "off",
			"no-eval": "off",
			"no-extend-native": "error",
			"no-extra-bind": "error",
			"no-extra-boolean-cast": "off",
			"no-extra-label": "off",
			"no-global-assign": "off",
			"no-implicit-coercion": "off",
			"no-implicit-globals": "off",
			"no-implied-eval": "off",
			"no-inline-comments": "error",
			"no-invalid-this": "error",
			"no-iterator": "error",
			"no-label-var": "off",
			"no-labels": "error",
			"no-lone-blocks": "off",
			"no-lonely-if": "off",
			"no-loop-func": "error",
			"no-magic-numbers": "off",
			"no-multi-assign": "off",
			"no-multi-str": "off",
			"no-negated-condition": "off",
			"no-nested-ternary": "off",
			"no-new": "off",
			"no-new-func": "error",
			"no-new-wrappers": "off",
			"no-nonoctal-decimal-escape": "off",
			"no-object-constructor": "error",
			"no-octal": "off",
			"no-octal-escape": "off",
			"no-param-reassign": "off",
			"no-plusplus": "off",
			"no-proto": "off",
			"no-redeclare": "off",
			"no-regex-spaces": "off",
			"no-restricted-exports": "off",
			"no-restricted-globals": "off",
			"no-restricted-properties": "off",
			"no-restricted-syntax": "off",
			"no-return-assign": "off",
			"no-script-url": "off",
			"no-sequences": "off",
			"no-shadow": "off",
			"no-shadow-restricted-names": "off",
			"no-ternary": "off",
			"no-throw-literal": "off",
			"no-unassigned-vars": "off",
			"no-undef-init": "off",
			"no-undefined": "off",
			"no-underscore-dangle": [
				"error",
				{
					enforceInMethodNames: true,
				},
			],
			"no-unneeded-ternary": "off",
			"no-unused-expressions": "off",
			"no-unused-labels": "off",
			"no-useless-call": "error",
			"no-useless-catch": "off",
			"no-useless-computed-key": "off",
			"no-useless-concat": "off",
			"no-useless-constructor": "off",
			"no-useless-escape": "off",
			"no-useless-rename": "off",
			"no-useless-return": "off",
			"no-var": "off",
			"no-void": "off",
			"no-warning-comments": "warn",
			"no-with": "off",
			"object-shorthand": "off",
			"one-var": "off",
			"operator-assignment": "off",
			"prefer-arrow-callback": "off",
			"prefer-const": "off",
			"prefer-destructuring": "off",
			"prefer-exponentiation-operator": "off",
			"prefer-named-capture-group": "off",
			"prefer-numeric-literals": "off",
			"prefer-object-has-own": "error",
			"prefer-object-spread": "off",
			"prefer-promise-reject-errors": "error",
			"prefer-regex-literals": "off",
			"prefer-rest-params": "off",
			"prefer-spread": "off",
			"prefer-template": "off",
			"preserve-caught-error": "off",
			radix: "off",
			"require-await": "off",
			"require-unicode-regexp": "off",
			"require-yield": "off",
			"sort-imports": "off",
			"sort-keys": "off",
			"sort-vars": "off",
			strict: ["error", "global"],
			"symbol-description": "off",
			"vars-on-top": "off",
			yoda: "off",

			// Layout & Formatting
			"line-comment-position": "off",
			"unicode-bom": "error",

			// @stylistic
			"@stylistic/jsx-child-element-spacing": "error",
			"@stylistic/jsx-curly-brace-presence": ["error", "always"],
			"@stylistic/jsx-pascal-case": "error",
			"@stylistic/max-statements-per-line": "off",
			"@stylistic/multiline-comment-style": ["error", "separate-lines"],
			"@stylistic/no-floating-decimal": "off",
			"@stylistic/no-mixed-operators": "off",
			"@stylistic/padding-line-between-statements": [
				"error",
				// return
				{
					blankLine: "always",
					prev: "*",
					next: "return",
				},
				// const, let, var
				{
					blankLine: "always",
					prev: ["const", "let", "var"],
					next: "*",
				},
				{
					blankLine: "always",
					prev: "*",
					next: ["const", "let", "var"],
				},
				{
					blankLine: "any",
					prev: ["const", "let", "var"],
					next: ["const", "let", "var"],
				},
				// import
				{
					blankLine: "always",
					prev: ["import", "cjs-import"],
					next: "*",
				},
				{
					blankLine: "never",
					prev: ["import", "cjs-import"],
					next: ["import", "cjs-import"],
				},
				// export
				{
					blankLine: "always",
					prev: "*",
					next: ["export", "cjs-export"],
				},
				{
					blankLine: "any",
					prev: ["export", "cjs-export"],
					next: ["export", "cjs-export"],
				},
				// function
				{
					blankLine: "always",
					prev: "*",
					next: "function",
				},
			],
			"@stylistic/quote-props": "off",
			"@stylistic/spaced-comment": ["error", "always"],

			// @eslint-react/eslint-plugin
			// X Rules
			"react/error-boundaries": "error",
			"react/exhaustive-deps": "off",
			"react/globals": "error",
			"react/immutability": "error",
			"react/no-access-state-in-setstate": "error",
			"react/no-array-index-key": "off",
			"react/no-children-count": "error",
			"react/no-children-for-each": "error",
			"react/no-children-map": "error",
			"react/no-children-only": "error",
			"react/no-children-to-array": "error",
			"react/no-class-component": "off",
			"react/no-clone-element": "error",
			"react/no-component-will-mount": "warn",
			"react/no-component-will-receive-props": "warn",
			"react/no-component-will-update": "warn",
			"react/no-context-provider": "warn",
			"react/no-create-ref": "warn",
			"react/no-direct-mutation-state": "error",
			"react/no-duplicate-key": "error",
			"react/no-forward-ref": "warn",
			// Requires type information
			"react/no-implicit-children": "off",
			// Requires type information
			"react/no-implicit-key": "off",
			// Requires type information
			"react/no-implicit-ref": "off",
			"react/no-leaked-conditional-rendering": "off",
			"react/no-missing-component-display-name": "warn",
			"react/no-missing-context-display-name": "warn",
			"react/no-missing-key": "off",
			"react/no-misused-capture-owner-stack": "error",
			"react/no-nested-component-definitions": "error",
			"react/no-nested-lazy-component-declarations": "error",
			"react/no-set-state-in-component-did-mount": "error",
			"react/no-set-state-in-component-did-update": "error",
			"react/no-set-state-in-component-will-update": "error",
			"react/no-unnecessary-use-prefix": "warn",
			"react/no-unsafe-component-will-mount": "error",
			"react/no-unsafe-component-will-receive-props": "error",
			"react/no-unsafe-component-will-update": "error",
			"react/no-unstable-context-value": "error",
			"react/no-unstable-default-props": "error",
			"react/no-unused-class-component-members": "error",
			// Requires type information
			"react/no-unused-props": "off",
			"react/no-unused-state": "error",
			"react/no-use-context": "warn",
			"react/purity": "error",
			"react/refs": "error",
			"react/rules-of-hooks": "error",
			"react/set-state-in-effect": "error",
			"react/set-state-in-render": "error",
			"react/static-components": "error",
			"react/unsupported-syntax": "error",
			"react/use-memo": "error",
			"react/use-state": "error",
			// JSX Rules
			"react/jsx-no-children-prop": "error",
			"react/jsx-no-children-prop-with-children": "error",
			"react/jsx-no-comment-textnodes": "error",
			"react/jsx-no-key-after-spread": "error",
			"react/jsx-no-leaked-dollar": "off",
			"react/jsx-no-leaked-semicolon": "error",
			"react/jsx-no-namespace": "off",
			"react/jsx-no-useless-fragment": "off",
			// RSC Rules
			"react/rsc-function-definition": "error",
			// DOM Rules
			"react/dom-no-dangerously-set-innerhtml": "off",
			"react/dom-no-dangerously-set-innerhtml-with-children": "off",
			"react/dom-no-find-dom-node": "error",
			"react/dom-no-flush-sync": "error",
			"react/dom-no-hydrate": "warn",
			"react/dom-no-missing-button-type": "off",
			"react/dom-no-missing-iframe-sandbox": "off",
			"react/dom-no-render": "warn",
			"react/dom-no-render-return-value": "error",
			"react/dom-no-script-url": "error",
			"react/dom-no-string-style-prop": "error",
			"react/dom-no-unknown-property": "off",
			"react/dom-no-unsafe-iframe-sandbox": "off",
			"react/dom-no-unsafe-target-blank": "off",
			"react/dom-no-use-form-state": "warn",
			"react/dom-no-void-elements-with-children": "off",
			// Web API Rules
			"react/web-api-no-leaked-event-listener": "error",
			"react/web-api-no-leaked-fetch": "error",
			"react/web-api-no-leaked-intersection-observer": "error",
			"react/web-api-no-leaked-interval": "error",
			"react/web-api-no-leaked-resize-observer": "error",
			"react/web-api-no-leaked-timeout": "error",
			// Naming Convention Rules
			"react/naming-convention-context-name": "warn",
			"react/naming-convention-id-name": "warn",
			"react/naming-convention-ref-name": "warn",

			// eslint-plugin-unicorn
			"unicorn/better-dom-traversing": "error",
			"unicorn/catch-error-name": [
				"error",
				{
					name: "ex",
					ignore: ["^ex([A-Z0-9].*)?$"],
				},
			],
			"unicorn/consistent-assert": "error",
			"unicorn/consistent-boolean-name": "warn",
			"unicorn/consistent-compound-words": "warn",
			"unicorn/consistent-conditional-object-spread": "error",
			"unicorn/consistent-date-clone": "error",
			"unicorn/consistent-destructuring": "error",
			"unicorn/consistent-empty-array-spread": "error",
			"unicorn/consistent-existence-index-check": "error",
			"unicorn/consistent-function-scoping": [
				"error",
				{
					checkArrowFunctions: false,
				},
			],
			"unicorn/consistent-json-file-read": "error",
			"unicorn/consistent-template-literal-escape": "error",
			"unicorn/consistent-tuple-labels": "error",
			"unicorn/custom-error-definition": "off",
			"unicorn/default-export-style": "error",
			"unicorn/dom-node-dataset": "error",
			"unicorn/empty-brace-spaces": "off",
			"unicorn/error-message": "off",
			"unicorn/escape-case": "error",
			"unicorn/expiring-todo-comments": "error",
			"unicorn/explicit-length-check": "off",
			"unicorn/filename-case": "off",
			"unicorn/import-style": "error",
			"unicorn/isolated-functions": "error",
			"unicorn/logical-assignment-operators": "error",
			"unicorn/name-replacements": "off",
			"unicorn/new-for-builtins": "off",
			"unicorn/no-abusive-eslint-disable": "error",
			"unicorn/no-accidental-bitwise-operator": "error",
			"unicorn/no-accessor-recursion": "error",
			"unicorn/no-anonymous-default-export": "error",
			"unicorn/no-array-callback-reference": "off",
			"unicorn/no-array-concat-in-loop": "error",
			"unicorn/no-array-fill-with-reference-type": "error",
			"unicorn/no-array-from-fill": "error",
			"unicorn/no-array-front-mutation": "error",
			"unicorn/no-array-method-this-argument": "error",
			"unicorn/no-array-reduce": "off",
			"unicorn/no-array-reverse": "error",
			"unicorn/no-array-sort": "error",
			"unicorn/no-array-sort-for-min-max": "error",
			"unicorn/no-array-splice": "error",
			"unicorn/no-await-expression-member": "error",
			"unicorn/no-async-promise-finally": "error",
			"unicorn/no-await-in-promise-methods": "error",
			"unicorn/no-blob-to-file": "error",
			"unicorn/no-boolean-sort-comparator": "error",
			"unicorn/no-break-in-nested-loop": "error",
			"unicorn/no-canvas-to-image": "error",
			"unicorn/no-chained-comparison": "error",
			"unicorn/no-collection-bracket-access": "error",
			"unicorn/no-confusing-array-splice": "error",
			"unicorn/no-confusing-array-with": "error",
			"unicorn/no-console-spaces": "error",
			"unicorn/no-constant-zero-expression": "error",
			"unicorn/no-declarations-before-early-exit": "error",
			"unicorn/no-document-cookie": "off",
			"unicorn/no-double-comparison": "error",
			"unicorn/no-duplicate-if-branches": "error",
			"unicorn/no-duplicate-logical-operands": "error",
			"unicorn/no-duplicate-loops": "error",
			"unicorn/no-duplicate-set-values": "error",
			"unicorn/no-empty-file": "error",
			"unicorn/no-error-property-assignment": "error",
			"unicorn/no-exports-in-scripts": "error",
			"unicorn/no-for-each": "off",
			"unicorn/no-for-loop": "off",
			"unicorn/no-global-object-property-assignment": "error",
			"unicorn/no-immediate-mutation": "error",
			"unicorn/no-impossible-length-comparison": "error",
			"unicorn/no-incorrect-query-selector": "error",
			"unicorn/no-incorrect-template-string-interpolation": "off",
			"unicorn/no-instanceof-array": "off",
			"unicorn/no-instanceof-builtins": "error",
			"unicorn/no-invalid-argument-count": "error",
			"unicorn/no-invalid-character-comparison": "error",
			"unicorn/no-invalid-fetch-options": "error",
			"unicorn/no-invalid-file-input-accept": "error",
			"unicorn/no-invalid-remove-event-listener": "error",
			"unicorn/no-invalid-well-known-symbol-methods": "error",
			"unicorn/no-keyword-prefix": "off",
			"unicorn/no-late-current-target-access": "error",
			"unicorn/no-late-event-control": "error",
			"unicorn/no-lonely-if": "off",
			"unicorn/no-loop-iterable-mutation": "error",
			"unicorn/no-magic-array-flat-depth": "error",
			"unicorn/no-manually-wrapped-comments": "error",
			"unicorn/no-mismatched-map-key": "error",
			"unicorn/no-misrefactored-assignment": "error",
			"unicorn/no-missing-local-resource": "off",
			"unicorn/no-multiple-promise-resolver-calls": "error",
			"unicorn/no-named-default": "error",
			"unicorn/no-negated-array-predicate": "error",
			"unicorn/no-negated-comparison": "error",
			"unicorn/no-negated-condition": "off",
			"unicorn/no-negation-in-equality-check": "off",
			"unicorn/no-nested-ternary": "off",
			"unicorn/no-new-array": "error",
			"unicorn/no-new-buffer": "error",
			"unicorn/no-non-function-verb-prefix": "off",
			"unicorn/no-nonstandard-builtin-properties": "error",
			"unicorn/no-null": "off",
			"unicorn/no-object-as-default-parameter": "error",
			"unicorn/no-object-methods-with-collections": "error",
			"unicorn/no-optional-chaining-on-undeclared-variable": "error",
			"unicorn/no-process-exit": "error",
			"unicorn/no-redundant-comparison": "error",
			"unicorn/no-return-array-push": "off",
			"unicorn/no-selector-as-dom-name": "error",
			"unicorn/no-shorthand-property-overrides": "off",
			"unicorn/no-single-promise-in-promise-methods": "error",
			"unicorn/no-static-only-class": "off",
			"unicorn/no-subtraction-comparison": "error",
			"unicorn/no-thenable": "off",
			"unicorn/no-this-assignment": "error",
			"unicorn/no-this-outside-of-class": "error",
			"unicorn/no-top-level-assignment-in-function": "error",
			"unicorn/no-top-level-side-effects": "error",
			"unicorn/no-transition-all": "off",
			"unicorn/no-unnecessary-array-flat-depth": "error",
			"unicorn/no-unnecessary-array-splice-count": "error",
			"unicorn/no-unnecessary-await": "error",
			"unicorn/no-unnecessary-boolean-comparison": "error",
			"unicorn/no-unnecessary-fetch-options": "error",
			"unicorn/no-unnecessary-global-this": "error",
			"unicorn/no-unnecessary-nested-ternary": "off",
			"unicorn/no-unnecessary-slice-end": "error",
			"unicorn/no-unnecessary-splice": "error",
			"unicorn/no-unnecessary-string-trim": "off",
			"unicorn/no-unreadable-array-destructuring": "error",
			"unicorn/no-unreadable-for-of-expression": "error",
			"unicorn/no-unreadable-iife": "error",
			"unicorn/no-unreadable-new-expression": "off",
			"unicorn/no-unreadable-object-destructuring": "error",
			"unicorn/no-unsafe-buffer-conversion": "error",
			"unicorn/no-unsafe-dom-html": "error",
			"unicorn/no-unsafe-promise-all-settled-values": "error",
			"unicorn/no-unsafe-property-key": "error",
			"unicorn/no-unsafe-string-replacement": "error",
			"unicorn/no-unused-array-method-return": "error",
			"unicorn/no-unused-properties": "error",
			"unicorn/no-useless-boolean-cast": "off",
			"unicorn/no-useless-coercion": "error",
			"unicorn/no-useless-collection-argument": "error",
			"unicorn/no-useless-compound-assignment": "error",
			"unicorn/no-useless-concat": "off",
			"unicorn/no-useless-continue": "off",
			"unicorn/no-useless-delete-check": "error",
			"unicorn/no-useless-else": "off",
			"unicorn/no-useless-error-capture-stack-trace": "error",
			"unicorn/no-useless-fallback-in-spread": "error",
			"unicorn/no-useless-iterator-to-array": "error",
			"unicorn/no-useless-length-check": "error",
			"unicorn/no-useless-logical-operand": "error",
			"unicorn/no-useless-override": "error",
			"unicorn/no-useless-promise-resolve-reject": "error",
			"unicorn/no-useless-re-export": "error",
			"unicorn/no-useless-recursion": "error",
			"unicorn/no-useless-spread": "error",
			"unicorn/no-useless-switch-case": "off",
			"unicorn/no-useless-template-literals": "off",
			"unicorn/no-useless-undefined": "off",
			"unicorn/no-typeof-undefined": "error",
			"unicorn/no-uncalled-method": "error",
			"unicorn/no-undeclared-class-members": "error",
			"unicorn/no-xor-as-exponentiation": "error",
			"unicorn/no-zero-fractions": "error",
			"unicorn/numeric-separators-style": "off",
			"unicorn/operator-assignment": "off",
			"unicorn/prefer-abort-signal-any": "error",
			"unicorn/prefer-abort-signal-timeout": "error",
			"unicorn/prefer-add-event-listener": "error",
			"unicorn/prefer-add-event-listener-options": "error",
			"unicorn/prefer-aggregate-error": "error",
			"unicorn/prefer-array-find": "error",
			"unicorn/prefer-array-flat": "error",
			"unicorn/prefer-array-flat-map": "off",
			"unicorn/prefer-array-from-async": "error",
			"unicorn/prefer-array-from-map": "error",
			"unicorn/prefer-array-from-range": "error",
			"unicorn/prefer-array-index-of": "off",
			"unicorn/prefer-array-iterable-methods": "error",
			"unicorn/prefer-array-last-methods": "error",
			"unicorn/prefer-array-slice": "off",
			"unicorn/prefer-array-some": "off",
			"unicorn/prefer-at": "off",
			"unicorn/prefer-await": "off",
			"unicorn/prefer-bigint-literals": "error",
			"unicorn/prefer-blob-reading-methods": "error",
			"unicorn/prefer-block-statement-over-iife": "error",
			"unicorn/prefer-boolean-return": "error",
			"unicorn/prefer-class-fields": "error",
			"unicorn/prefer-classlist-toggle": "error",
			"unicorn/prefer-code-point": "error",
			"unicorn/prefer-continue": "error",
			"unicorn/prefer-date-now": "off",
			"unicorn/prefer-default-parameters": "error",
			"unicorn/prefer-direct-iteration": "error",
			"unicorn/prefer-dispose": "error",
			"unicorn/prefer-dom-node-append": "error",
			"unicorn/prefer-dom-node-html-methods": "error",
			"unicorn/prefer-dom-node-remove": "error",
			"unicorn/prefer-dom-node-replace-children": "error",
			"unicorn/prefer-dom-node-text-content": "off",
			"unicorn/prefer-early-return": "error",
			"unicorn/prefer-else-if": "off",
			"unicorn/prefer-error-is-error": "error",
			"unicorn/prefer-event-target": "off",
			"unicorn/prefer-explicit-viewport-units": "off",
			"unicorn/prefer-export-from": "off",
			"unicorn/prefer-flat-math-min-max": "error",
			"unicorn/prefer-get-or-insert-computed": "error",
			"unicorn/prefer-global-number-constants": "off",
			"unicorn/prefer-global-this": "off",
			"unicorn/prefer-group-by": "error",
			"unicorn/prefer-has-check": "error",
			"unicorn/prefer-hoisting-branch-code": "error",
			"unicorn/prefer-https": "error",
			"unicorn/prefer-identifier-import-export-specifiers": "error",
			"unicorn/prefer-import-meta-properties": "error",
			"unicorn/prefer-includes": "error",
			"unicorn/prefer-includes-over-repeated-comparisons": "error",
			"unicorn/prefer-iterable-in-constructor": "error",
			"unicorn/prefer-iterator-concat": "error",
			"unicorn/prefer-iterator-helpers": "error",
			"unicorn/prefer-iterator-to-array": "error",
			"unicorn/prefer-iterator-to-array-at-end": "error",
			"unicorn/prefer-json-parse-buffer": "error",
			"unicorn/prefer-keyboard-event-key": "error",
			"unicorn/prefer-location-assign": "error",
			"unicorn/prefer-logical-operator-over-ternary": "error",
			"unicorn/prefer-map-from-entries": "error",
			"unicorn/prefer-math-abs": "error",
			"unicorn/prefer-math-constants": "error",
			"unicorn/prefer-math-min-max": "off",
			"unicorn/prefer-math-trunc": "error",
			"unicorn/prefer-minimal-ternary": "error",
			"unicorn/prefer-modern-dom-apis": "error",
			"unicorn/prefer-modern-math-apis": "error",
			"unicorn/prefer-module": "off",
			"unicorn/prefer-native-coercion-functions": "error",
			"unicorn/prefer-negative-index": "error",
			"unicorn/prefer-node-protocol": "off",
			"unicorn/prefer-number-coercion": "error",
			"unicorn/prefer-number-is-safe-integer": "error",
			"unicorn/prefer-number-properties": "off",
			"unicorn/prefer-object-define-properties": "error",
			"unicorn/prefer-object-destructuring-defaults": "error",
			"unicorn/prefer-object-from-entries": "error",
			"unicorn/prefer-object-iterable-methods": "error",
			"unicorn/prefer-observer-apis": "error",
			"unicorn/prefer-optional-catch-binding": "off",
			"unicorn/prefer-path2d": "off",
			"unicorn/prefer-private-class-fields": "error",
			"unicorn/prefer-promise-try": "error",
			"unicorn/prefer-promise-with-resolvers": "error",
			"unicorn/prefer-prototype-methods": "off",
			"unicorn/prefer-query-selector": "off",
			"unicorn/prefer-queue-microtask": "error",
			"unicorn/prefer-reflect-apply": "error",
			"unicorn/prefer-regexp-escape": "error",
			"unicorn/prefer-regexp-test": "off",
			"unicorn/prefer-response-static-json": "error",
			"unicorn/prefer-scoped-selector": "error",
			"unicorn/prefer-set-has": "error",
			"unicorn/prefer-set-methods": "error",
			"unicorn/prefer-set-size": "error",
			"unicorn/prefer-short-arrow-method": "off",
			"unicorn/prefer-simple-condition-first": "warn",
			"unicorn/prefer-simple-sort-comparator": "error",
			"unicorn/prefer-simplified-conditions": "error",
			"unicorn/prefer-single-array-predicate": "error",
			"unicorn/prefer-single-call": "error",
			"unicorn/prefer-single-object-destructuring": "error",
			"unicorn/prefer-single-replace": "error",
			"unicorn/prefer-smaller-scope": "error",
			"unicorn/prefer-split-limit": "error",
			"unicorn/prefer-spread": "error",
			"unicorn/prefer-string-match-all": "error",
			"unicorn/prefer-string-pad-start-end": "error",
			"unicorn/prefer-string-raw": "error",
			"unicorn/prefer-string-repeat": "error",
			"unicorn/prefer-string-replace-all": "error",
			"unicorn/prefer-string-slice": "off",
			"unicorn/prefer-string-starts-ends-with": "off",
			"unicorn/prefer-string-trim-start-end": "off",
			"unicorn/prefer-structured-clone": "error",
			"unicorn/prefer-switch": "error",
			"unicorn/prefer-temporal": "off",
			// TODO: off until there is a solution to this: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1079
			"unicorn/prefer-ternary": "off",
			"unicorn/prefer-then-catch": "error",
			"unicorn/prefer-toggle-attribute": "error",
			"unicorn/prefer-top-level-await": "off",
			"unicorn/prefer-type-error": "error",
			"unicorn/prefer-type-literal-last": "off",
			"unicorn/prefer-uint8array-base64": "error",
			"unicorn/prefer-unary-minus": "error",
			"unicorn/prefer-unicode-code-point-escapes": "error",
			"unicorn/prefer-url-can-parse": "error",
			"unicorn/prefer-url-href": "error",
			"unicorn/prefer-url-search-parameters": "error",
			"unicorn/prefer-while-loop-condition": "error",
			"unicorn/relative-url-style": "error",
			"unicorn/require-array-join-separator": "error",
			"unicorn/require-array-sort-compare": "off",
			"unicorn/require-css-escape": "error",
			"unicorn/require-frontmatter-fields": "off",
			"unicorn/require-module-attributes": "error",
			"unicorn/require-module-specifiers": "off",
			"unicorn/require-number-to-fixed-digits-argument": "off",
			"unicorn/require-passive-events": "error",
			"unicorn/require-post-message-target-origin": "error",
			"unicorn/require-proxy-trap-boolean-return": "error",
			"unicorn/string-content": "off",
			"unicorn/switch-case-braces": "off",
			"unicorn/switch-case-break-position": "error",
			"unicorn/template-indent": "off",
			"unicorn/text-encoding-identifier-case": "error",
			"unicorn/throw-new-error": "off",

			// eslint-plugin-import
			"importPlugin/export": "off",
			"importPlugin/no-deprecated": "off",
			"importPlugin/no-empty-named-blocks": "error",
			"importPlugin/no-extraneous-dependencies": "off",
			"importPlugin/no-mutable-exports": "error",
			"importPlugin/no-named-as-default": "error",
			"importPlugin/no-named-as-default-member": "off",
			"importPlugin/no-unused-modules": "off",
			"importPlugin/no-amd": "off",
			"importPlugin/no-commonjs": "off",
			"importPlugin/no-import-module-exports": "off",
			"importPlugin/no-nodejs-modules": "off",
			"importPlugin/unambiguous": "off",
			"importPlugin/default": "off",
			"importPlugin/named": "off",
			"importPlugin/namespace": "off",
			"importPlugin/no-absolute-path": "error",
			"importPlugin/no-cycle": "off",
			"importPlugin/no-dynamic-require": "off",
			"importPlugin/no-internal-modules": "off",
			"importPlugin/no-relative-packages": "off",
			"importPlugin/no-relative-parent-imports": "off",
			"importPlugin/no-restricted-paths": "off",
			"importPlugin/no-self-import": "error",
			"importPlugin/no-unresolved": "off",
			"importPlugin/no-useless-path-segments": [
				"error",
				{
					noUselessIndex: true,
				},
			],
			"importPlugin/no-webpack-loader-syntax": "error",
			"importPlugin/consistent-type-specifier-style": "off",
			"importPlugin/dynamic-import-chunkname": "off",
			"importPlugin/exports-last": "off",
			"importPlugin/extensions": "off",
			"importPlugin/first": "error",
			"importPlugin/group-exports": "error",
			"importPlugin/max-dependencies": "off",
			"importPlugin/newline-after-import": "off",
			"importPlugin/no-anonymous-default-export": "error",
			"importPlugin/no-default-export": "off",
			"importPlugin/no-duplicates": ["error", { "prefer-inline": true }],
			"importPlugin/no-named-default": "off",
			"importPlugin/no-named-export": "off",
			"importPlugin/no-namespace": "off",
			"importPlugin/no-rename-default": "off",
			"importPlugin/no-unassigned-import": "off",
			"importPlugin/order": "off",
			"importPlugin/prefer-default-export": "off",
			"importPlugin/prefer-namespace-import": "off",
		},
	},
	{
		files: ["**/*.ts", "**/*.tsx"],
		plugins: {
			"@typescript-eslint": typescriptEslint,
		},
		languageOptions: {
			parser: tsParser,
			sourceType: "module",
			parserOptions: {
				projectService: true,
				tsconfigRootDir: import.meta.dirname,
			},
		},
		rules: {
			// Typescript
			"@typescript-eslint/adjacent-overload-signatures": "off",
			"@typescript-eslint/array-type": "off",
			"@typescript-eslint/await-thenable": "error",
			"@typescript-eslint/ban-ts-comment": "off",
			"@typescript-eslint/ban-tslint-comment": "error",
			"@typescript-eslint/ban-types": "off",
			"@typescript-eslint/class-literal-property-style": "error",
			"class-methods-use-this": "off",
			"@typescript-eslint/class-methods-use-this": "off",
			"@typescript-eslint/consistent-generic-constructors": "error",
			"@typescript-eslint/consistent-indexed-object-style": "error",
			"@typescript-eslint/consistent-type-assertions": "error",
			"@typescript-eslint/consistent-type-definitions": "off",
			"@typescript-eslint/consistent-type-exports": "off",
			"@typescript-eslint/consistent-type-imports": "off",
			"default-param-last": "off",
			"@typescript-eslint/default-param-last": "off",
			"dot-notation": "off",
			"@typescript-eslint/dot-notation": "off",
			"@typescript-eslint/explicit-function-return-type": [
				"error",
				{
					allowExpressions: true,
					allowTypedFunctionExpressions: true,
					allowHigherOrderFunctions: true,
					allowDirectConstAssertionInArrowFunctions: true,
					allowConciseArrowFunctionExpressionsStartingWithVoid: false,
				},
			],
			"@typescript-eslint/explicit-member-accessibility": "off",
			"@typescript-eslint/explicit-module-boundary-types": "off",
			"init-declarations": "off",
			"@typescript-eslint/init-declarations": "off",
			"@typescript-eslint/max-params": "off",
			"@typescript-eslint/member-ordering": "off",
			"@typescript-eslint/method-signature-style": "off",
			"@typescript-eslint/naming-convention": "off",
			"no-array-constructor": "off",
			"@typescript-eslint/no-array-constructor": "off",
			"@typescript-eslint/no-array-delete": "off",
			"@typescript-eslint/no-base-to-string": "off",
			"@typescript-eslint/no-confusing-non-null-assertion": "error",
			"@typescript-eslint/no-confusing-void-expression": "off",
			"@typescript-eslint/no-deprecated": "off",
			"no-dupe-class-members": "off",
			"@typescript-eslint/no-dupe-class-members": "off",
			"@typescript-eslint/no-duplicate-enum-values": "error",
			"@typescript-eslint/no-duplicate-type-constituents": "error",
			"@typescript-eslint/no-dynamic-delete": "error",
			"no-empty-function": "off",
			"@typescript-eslint/no-empty-function": "off",
			"@typescript-eslint/no-empty-interface": "off",
			"@typescript-eslint/no-empty-object-type": "off",
			"@typescript-eslint/no-explicit-any": "off",
			"@typescript-eslint/no-extra-non-null-assertion": "off",
			"@typescript-eslint/no-extraneous-class": "error",
			"@typescript-eslint/no-floating-promises": "off",
			"@typescript-eslint/no-for-in-array": "off",
			"@typescript-eslint/no-implied-eval": "off",
			"@typescript-eslint/no-import-type-side-effects": "off",
			"@typescript-eslint/no-inferrable-types": "off",
			"no-invalid-this": "off",
			"@typescript-eslint/no-invalid-this": "error",
			"@typescript-eslint/no-invalid-void-type": "off",
			"no-loop-func": "off",
			"@typescript-eslint/no-loop-func": "off",
			"no-magic-numbers": "off",
			"@typescript-eslint/no-magic-numbers": "off",
			"@typescript-eslint/no-meaningless-void-operator": "off",
			"@typescript-eslint/no-misused-new": "off",
			"@typescript-eslint/no-misused-promises": "off",
			"@typescript-eslint/no-misused-spread": "error",
			"@typescript-eslint/no-mixed-enums": "off",
			"@typescript-eslint/no-namespace": "off",
			"@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
			"@typescript-eslint/no-non-null-asserted-optional-chain": "off",
			"@typescript-eslint/no-non-null-assertion": "off",
			"no-redeclare": "off",
			"@typescript-eslint/no-redeclare": "off",
			"@typescript-eslint/no-redundant-type-constituents": "error",
			"@typescript-eslint/no-require-imports": "off",
			"@typescript-eslint/no-restricted-types": "off",
			"no-shadow": "off",
			"@typescript-eslint/no-shadow": "off",
			"@typescript-eslint/no-this-alias": "off",
			"@typescript-eslint/no-type-alias": "off",
			"@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
			"@typescript-eslint/no-unnecessary-condition": "off",
			"@typescript-eslint/no-unnecessary-parameter-property-assignment":
				"error",
			"@typescript-eslint/no-unnecessary-qualifier": "error",
			"@typescript-eslint/no-unnecessary-template-expression": "off",
			"@typescript-eslint/no-unnecessary-type-arguments": "error",
			"@typescript-eslint/no-unnecessary-type-assertion": "error",
			"@typescript-eslint/no-unnecessary-type-constraint": "off",
			"@typescript-eslint/no-unnecessary-type-conversion": "off",
			"@typescript-eslint/no-unnecessary-type-parameters": "error",
			"@typescript-eslint/no-unsafe-argument": "error",
			"@typescript-eslint/no-unsafe-assignment": "error",
			"@typescript-eslint/no-unsafe-call": "error",
			"@typescript-eslint/no-unsafe-declaration-merging": "off",
			"@typescript-eslint/no-unsafe-enum-comparison": "error",
			"@typescript-eslint/no-unsafe-function-type": "off",
			"@typescript-eslint/no-unsafe-member-access": "error",
			"@typescript-eslint/no-unsafe-return": "error",
			"@typescript-eslint/no-unsafe-type-assertion": "error",
			"@typescript-eslint/no-unsafe-unary-minus": "error",
			"no-unused-expressions": "off",
			"@typescript-eslint/no-unused-expressions": "off",
			"no-unused-private-class-members": "off",
			"@typescript-eslint/no-unused-private-class-members": "off",
			"no-unused-vars": "off",
			"@typescript-eslint/no-unused-vars": "off",
			"no-use-before-define": "off",
			"@typescript-eslint/no-use-before-define": "off",
			"no-useless-constructor": "off",
			"@typescript-eslint/no-useless-constructor": "off",
			"@typescript-eslint/no-useless-default-assignment": "error",
			"@typescript-eslint/no-useless-empty-export": "off",
			"@typescript-eslint/no-var-requires": "off",
			"@typescript-eslint/no-wrapper-object-types": "off",
			"@typescript-eslint/non-nullable-type-assertion-style": "off",
			"no-throw-literal": "off",
			"@typescript-eslint/only-throw-error": "off",
			"@typescript-eslint/parameter-properties": "off",
			"@typescript-eslint/prefer-as-const": "off",
			"@typescript-eslint/prefer-destructuring": "off",
			"@typescript-eslint/prefer-enum-initializers": "off",
			// unicorns prefer-array-find is more powerful
			"@typescript-eslint/prefer-find": "off",
			"@typescript-eslint/prefer-for-of": "off",
			"@typescript-eslint/prefer-function-type": "off",
			// unicorns prefer-includes is more powerful
			"@typescript-eslint/prefer-includes": "off",
			"@typescript-eslint/prefer-literal-enum-member": "off",
			"@typescript-eslint/prefer-namespace-keyword": "off",
			"@typescript-eslint/prefer-nullish-coalescing": "off",
			"@typescript-eslint/prefer-optional-chain": "off",
			"prefer-promise-reject-errors": "off",
			"@typescript-eslint/prefer-promise-reject-errors": "error",
			"@typescript-eslint/prefer-readonly": "off",
			"@typescript-eslint/prefer-readonly-parameter-types": "off",
			"@typescript-eslint/prefer-reduce-type-parameter": "off",
			"@typescript-eslint/prefer-regexp-exec": "off",
			"@typescript-eslint/prefer-return-this-type": "error",
			"@typescript-eslint/prefer-string-starts-ends-with": "error",
			"@typescript-eslint/promise-function-async": "error",
			"@typescript-eslint/related-getter-setter-pairs": "error",
			"@typescript-eslint/require-array-sort-compare": "off",
			"require-await": "off",
			"@typescript-eslint/require-await": "off",
			"@typescript-eslint/restrict-plus-operands": "off",
			"@typescript-eslint/restrict-template-expressions": "off",
			"@typescript-eslint/return-await": "off",
			"@typescript-eslint/strict-boolean-expressions": "off",
			"@typescript-eslint/strict-void-return": "off",
			"@typescript-eslint/switch-exhaustiveness-check": "off",
			"@typescript-eslint/triple-slash-reference": "error",
			"@typescript-eslint/typedef": "off",
			"@typescript-eslint/unbound-method": [
				"error",
				{
					ignoreStatic: true,
				},
			],
			"@typescript-eslint/unified-signatures": "off",
			"@typescript-eslint/use-unknown-in-catch-callback-variable": "error",

			// @eslint-react/eslint-plugin
			// X Rules
			"react/no-implicit-children": "error",
			"react/no-implicit-key": "error",
			"react/no-implicit-ref": "error",
			"react/no-unused-props": "error",

			// Typescript handles itself
			"consistent-return": "off",
			"@typescript-eslint/consistent-return": "off",
			"constructor-super": "off",
			"getter-return": "off",
			"no-class-assign": "off",
			"no-const-assign": "off",
			"no-delete-var": "off",
			"no-dupe-args": "off",
			"no-dupe-keys": "off",
			"no-func-assign": "off",
			"no-import-assign": "off",
			"no-new-symbol": "off",
			"no-nonoctal-decimal-escape": "off",
			"no-obj-calls": "off",
			"no-octal-escape": "off",
			"no-setter-return": "off",
			"no-shadow-restricted-names": "off",
			"no-undef": "off",
			"no-undefined": "off",
			"no-unexpected-multiline": "off",
			"no-unsafe-negation": "off",
			"no-with": "off",
			"valid-typeof": "off",
		},
	},
	{
		files: [
			"**/*.spec.ts",
			"**/*.spec.tsx",
			"**/*.test.ts",
			"**/*.test.tsx",
			"**/*.spec.js",
			"**/*.spec.jsx",
			"**/*.test.js",
			"**/*.test.jsx",
		],
		plugins: {
			jest,
			"testing-library": testingLibrary,
		},
		rules: {
			// eslint-plugin-jest
			"jest/consistent-test-it": "off",
			"jest/expect-expect": "off",
			"jest/max-expects": "off",
			"jest/max-nested-describe": "off",
			"jest/no-alias-methods": "error",
			"jest/no-commented-out-tests": "error",
			"jest/no-conditional-expect": "off",
			"jest/no-conditional-in-test": "error",
			"jest/no-confusing-set-timeout": "error",
			"jest/no-deprecated-functions": "warn",
			"jest/no-disabled-tests": "off",
			"jest/no-done-callback": "off",
			"jest/no-duplicate-hooks": "off",
			"jest/no-error-equal": "error",
			"jest/no-export": "off",
			"jest/no-focused-tests": "off",
			"jest/no-hooks": "off",
			"jest/no-identical-title": "off",
			"jest/no-interpolation-in-snapshots": "error",
			"jest/no-jasmine-globals": "error",
			"jest/no-large-snapshots": "off",
			"jest/no-mocks-import": "error",
			"jest/no-restricted-jest-methods": "off",
			"jest/no-restricted-matchers": "off",
			"jest/no-standalone-expect": "off",
			"jest/no-test-prefixes": "error",
			"jest/no-test-return-statement": "error",
			"jest/no-unnecessary-assertion": "error",
			"jest/no-unneeded-async-expect-function": "error",
			// This rule is only active if using typescript - see down below
			"jest/no-untyped-mock-factory": "off",
			"jest/padding-around-after-all-blocks": "off",
			"jest/padding-around-after-each-blocks": "off",
			"jest/padding-around-before-all-blocks": "off",
			"jest/padding-around-before-each-blocks": "off",
			"jest/padding-around-expect-groups": "off",
			"jest/padding-around-describe-blocks": "error",
			"jest/padding-around-test-blocks": "error",
			"jest/prefer-called-with": "error",
			"jest/prefer-comparison-matcher": "error",
			"jest/prefer-each": "error",
			"jest/prefer-ending-with-an-expect": "error",
			"jest/prefer-equality-matcher": "error",
			"jest/prefer-expect-assertions": "off",
			"jest/prefer-expect-resolves": "error",
			"jest/prefer-hooks-in-order": "off",
			"jest/prefer-hooks-on-top": "off",
			"jest/prefer-importing-jest-globals": "off",
			"jest/prefer-jest-mocked": "error",
			"jest/prefer-lowercase-title": [
				"error",
				{
					ignore: ["describe"],
				},
			],
			"jest/prefer-mock-promise-shorthand": "error",
			"jest/prefer-mock-return-shorthand": "error",
			"jest/prefer-snapshot-hint": "error",
			"jest/prefer-spy-on": "error",
			"jest/prefer-strict-equal": "error",
			"jest/prefer-to-be": "error",
			"jest/prefer-to-contain": "error",
			"jest/prefer-to-have-been-called": "off",
			"jest/prefer-to-have-been-called-times": "error",
			"jest/prefer-to-have-length": "error",
			"jest/prefer-todo": "warn",
			"jest/require-hook": "error",
			"jest/require-to-throw-message": "error",
			"jest/require-top-level-describe": "error",
			"@typescript-eslint/unbound-method": "off",
			"jest/unbound-method": "error",
			"jest/valid-describe-callback": "error",
			"jest/valid-expect": "error",
			"jest/valid-expect-in-promise": "error",
			"jest/valid-expect-with-promise": "error",
			"jest/valid-mock-module-path": "error",
			"jest/valid-title": "error",

			// plugin-testing-library
			"testing-library/await-async-events": "error",
			"testing-library/await-async-queries": "error",
			"testing-library/await-async-utils": "error",
			"testing-library/consistent-data-testid": "off",
			"testing-library/no-await-sync-events": "off",
			"testing-library/no-await-sync-queries": "off",
			"testing-library/no-container": "error",
			"testing-library/no-debugging-utils": "error",
			"testing-library/no-dom-import": ["error", "react"],
			"testing-library/no-global-regexp-flag-in-query": "error",
			"testing-library/no-manual-cleanup": "error",
			"testing-library/no-node-access": "error",
			"testing-library/no-promise-in-fire-event": "off",
			"testing-library/no-render-in-lifecycle": "error",
			"testing-library/no-test-id-queries": "error",
			"testing-library/no-unnecessary-act": "error",
			"testing-library/no-wait-for-multiple-assertions": "error",
			"testing-library/no-wait-for-side-effects": "error",
			"testing-library/no-wait-for-snapshot": "error",
			"testing-library/prefer-explicit-assert": "error",
			"testing-library/prefer-implicit-assert": "off",
			"testing-library/prefer-find-by": "error",
			"testing-library/prefer-presence-queries": "error",
			"testing-library/prefer-query-by-disappearance": "error",
			"testing-library/prefer-query-matchers": "off",
			"testing-library/prefer-screen-queries": "error",
			"testing-library/prefer-user-event": "error",
			"testing-library/prefer-user-event-setup": "error",
			"testing-library/render-result-naming-convention": "off",
		},
	},
	{
		files: ["**/*.spec.ts", "**/*.spec.tsx", "**/*.test.ts", "**/*.test.tsx"],
		plugins: {
			jest,
		},
		rules: {
			// eslint-plugin-jest
			"jest/no-untyped-mock-factory": "error",
		},
	},
];
